Repository Codeit-Sprint-6th-Part-4-Team-6/Teamagotchi, pull requests merged in 2024-07, with the labels that each got.

#1 📜 DOCS: pull_request_template.md 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📜 DOCS

#3 ⚙️ CHORE: 프로젝트 폴더 구조 추가 및 ESLint 설정
  .eslintrc.json
  .gitignore
  .prettierrc.json
  @types/.gitkeep
  README.md
  next.config.mjs
  package.json
  postcss.config.mjs
  public/favicon.ico
  public/icons/.gitkeep
  public/images/.gitkeep
  src/api/.gitkeep
  src/components/commons/.gitkeep
  src/components/login/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/styles/globals.css
  src/utils/.gitkeep
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: ⚙️ CHORE

#4 ⚙️ CHORE: husky 세팅
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  .prettierrc.json
  commitlint.config.ts
  package.json
  src/pages/_app.tsx
  src/pages/index.tsx
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: ⚙️ CHORE

#5 ⚙️ CHORE: 컬러 팔레트, 로컬 폰트, 다크 모드 세팅, 기타 패키지 추가
  .prettierignore
  package.json
  public/fonts/PretendardVariable.woff2
  src/pages/_app.tsx
  src/pages/index.tsx
  tailwind.config.ts
  yarn.lock
Labels: ⚙️ CHORE

#6 ✨ FEATURE: Input 컴포넌트 추가
  .prettierrc.json
  public/icons/.gitkeep
  public/icons/ic_search.svg
  public/icons/ic_visibility_off.svg
  public/icons/ic_visibility_on.svg
  public/icons/ic_x.svg
  src/components/commons/.gitkeep
  src/components/commons/Input/index.tsx
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ FEATURE

#8 ✨ FEATURE: storybook 설정
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  src/components/commons/ButtonEx/ButtonEx.tsx
  src/components/commons/ButtonEx/index.stories.tsx
  src/stories/colors.mdx
  yarn.lock
Labels: ✨ FEATURE

#7 ✨ FEATURE: 타입 / API 설정
  @types/.gitkeep
  @types/auth.ts
  @types/comment.ts
  @types/commons.ts
  @types/group.ts
  @types/task.ts
  @types/taskList.ts
  @types/user.ts
  package.json
  src/api/.gitkeep
  src/components/commons/ButtonEx/ButtonEx.tsx
  src/components/commons/ButtonEx/index.stories.tsx
  src/pages/api/authApi.ts
  src/pages/api/axios.ts
  src/pages/api/commentApi.ts
  src/pages/api/groupApi.ts
  src/pages/api/hello.ts
  src/pages/api/imageApi.ts
  src/pages/api/taskApi.ts
  src/pages/api/taskListApi.ts
  src/pages/api/userApi.ts
  yarn.lock
Labels: ✨ FEATURE

#12 ✨ FEATURE: 회원가입 시 서버에 POST 요청
  package.json
  src/pages/register.tsx
  src/store/useAuthStore.ts
  yarn.lock
Labels: ✨ FEATURE
