Repository Codeit-Sprint-6th-Part-4-Team-6/Teamagotchi, pull requests merged in 2024-08, with the labels that each got.

#11 ✨ FEATURE: 흘러간 시간 계산, 날짜 정렬하는 유틸 함수 추가
  @types/auth.ts
  @types/comment.ts
  @types/date.ts
  @types/group.ts
  @types/task.ts
  @types/taskList.ts
  @types/user.ts
  src/utils/.gitkeep
  src/utils/calculateElapsedTime.ts
  src/utils/formatDate.ts
Labels: ✨ FEATURE

#9 ✨ FEATURE: Label 컴포넌트 추가
  src/components/commons/Label/index.tsx
  src/pages/index.tsx
Labels: ✨ FEATURE

#10 ✨ FEATURE: 아이콘 컴포넌트화
  @types/svg.d.ts
  next.config.mjs
  package.json
  public/icons/icon_alert.svg
  public/icons/icon_arrow_left.svg
  public/icons/icon_arrow_left_bg.svg
  public/icons/icon_arrow_right.svg
  public/icons/icon_arrow_right_bg.svg
  public/icons/icon_calendar.svg
  public/icons/icon_check_active.svg
  public/icons/icon_check_disactive.svg
  public/icons/icon_checkbox_active.svg
  public/icons/icon_checkbox_default.svg
  public/icons/icon_close.svg
  public/icons/icon_comment.svg
  public/icons/icon_default_image.svg
  public/icons/icon_done.svg
  public/icons/icon_edit_large.svg
  public/icons/icon_edit_small.svg
  public/icons/icon_enter_active.svg
  public/icons/icon_enter_default.svg
  public/icons/icon_gear.svg
  public/icons/icon_gnb_menu.svg
  public/icons/icon_image.svg
  public/icons/icon_kebab_large.svg
  public/icons/icon_kebab_small.svg
  public/icons/icon_list.svg
  public/icons/icon_plus.svg
  public/icons/icon_progress_done.svg
  public/icons/icon_progress_ongoing.svg
  public/icons/icon_repair_large.svg
  public/icons/icon_repair_medium.svg
  public/icons/icon_repair_small.svg
  public/icons/icon_repeat.svg
  public/icons/icon_time.svg
  public/icons/icon_toggle.svg
  public/icons/icon_user.svg
  public/icons/icon_visibility_off.svg
  public/icons/icon_visibility_on.svg
  src/pages/api/authApi.ts
  src/pages/api/axios.ts
  src/pages/api/commentApi.ts
  src/pages/api/groupApi.ts
  src/pages/api/imageApi.ts
  src/pages/api/taskApi.ts
  src/pages/api/taskListApi.ts
  src/pages/api/userApi.ts
  src/utils/icon.ts
  yarn.lock
Labels: ✨ FEATURE

#13 ✨ FEATURE: 로그인 기능, axios 인터셉터 추가
  package.json
  src/pages/api/axios.ts
  src/pages/login.tsx
  src/pages/register.tsx
  src/pages/team-list.tsx
  src/store/useAuthStore.ts
  src/utils/auth.ts
  yarn.lock
Labels: ✨ FEATURE

#16 🎨 STYLE: svg 컴포넌트로 변경, height 스타일 변경
  public/icons/ic_visibility_off.svg
  public/icons/ic_visibility_on.svg
  public/icons/ic_x.svg
  public/icons/icon_search.svg
  public/icons/icon_visibility_on.svg
  src/components/commons/Input/index.tsx
  src/pages/index.tsx
  src/utils/icon.ts
Labels: 🎨 STYLE

#15 ✨ FEATURE: Textarea 컴포넌트 추가
  src/components/commons/TextArea/index.stories.tsx
  src/components/commons/TextArea/index.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: ✨ FEATURE

#17 ✨ FEATURE: SocialLoginBox Component(ui only) 추가
  public/icons/icon_google.svg
  public/icons/icon_kakaotalk.svg
  public/icons/icon_member.svg
  src/components/commons/SocialLoginBox/index.stories.tsx
  src/components/commons/SocialLoginBox/index.tsx
  src/utils/icon.ts
Labels: ✨ FEATURE

#19 ✨ FEATURE : 버튼 컴포넌트 생성
  .storybook/preview.ts
  package.json
  public/icons/icon_check_disactive.svg
  public/icons/icon_plus.svg
  src/components/commons/Button/Button.stories.tsx
  src/components/commons/Button/LinkButton/index.tsx
  src/components/commons/Button/TextButton/TextButton.stories.tsx
  src/components/commons/Button/TextButton/index.tsx
  src/components/commons/Button/index.tsx
  src/components/commons/ButtonEx/ButtonEx.tsx
  src/components/commons/ButtonEx/index.stories.tsx
  src/pages/index.tsx
  src/stories/colors.mdx
  tailwind.config.ts
  yarn.lock
Labels: ✨ FEATURE

#14 ✨ FEATURE: modal 컴포넌트 추가
  .env
  .eslintrc.json
  src/components/commons/Button/index.tsx
  src/components/commons/modal/ConfirmModal.tsx
  src/components/commons/modal/CustomModal.tsx
  src/components/commons/modal/ModalWrapper.stories.tsx
  src/components/commons/modal/ModalWrapper.tsx
  src/components/commons/modal/OneInputModal.tsx
  src/components/commons/modal/TwoInputModal.tsx
  src/components/commons/modal/WarnModal.tsx
  src/hooks/useModal.ts
  src/pages/_app.tsx
  src/store/stories/colors.mdx
  src/store/useModalStore.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ FEATURE

#20 ✨ FEATURE: added NameTag Component (FE-20)
  public/icons/icon_member.svg
  public/icons/icon_user.svg
  src/components/commons/NameTag/index.stories.tsx
  src/components/commons/NameTag/index.tsx
  src/pages/index.tsx
  src/styles/globals.css
  src/utils/icon.ts
Labels: ✨ FEATURE

#23 ♻️ REFACTOR: props에 onChange 추가
  src/components/commons/modal/OneInputModal.tsx
  src/components/commons/modal/TwoInputModal.tsx
Labels: ♻️ REFACTOR

#22 ⚙️ CHORE: tanstack 설치 및 적용
  package.json
  src/pages/_app.tsx
  yarn.lock
Labels: ⚙️ CHORE

#24 ✨ FEATURE: 비밀번호 재설정 기능 추가
  src/components/auth/ResetPasswordForm.tsx
  src/components/auth/SendMailModal.tsx
  src/components/login/.gitkeep
  src/hooks/.gitkeep
  src/pages/api/authApi.ts
  src/pages/api/userApi.ts
  src/pages/login.tsx
  src/pages/register.tsx
  src/pages/reset-password.tsx
  src/pages/team-list.tsx
Labels: ✨ FEATURE

#26 ✨ FEATURE: Popover 구현
  public/images/cute.jpeg
  public/images/dog.jpg
  src/components/commons/Popover/EditDeletePopover.tsx
  src/components/commons/Popover/ProfilePopover.tsx
  src/components/commons/Popover/TeamListPopover.tsx
  src/components/commons/Popover/index.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: ✨ FEATURE

#28 ✨ FEATURE: auth 관련 로직 분리, 유효성 검사, 버튼 disabled 처리
  package.json
  src/components/auth/LoginForm.tsx
  src/components/auth/RegisterForm.tsx
  src/components/auth/ResetPasswordForm.tsx
  src/components/commons/Button/index.tsx
  src/hooks/auth/useAuthForm.ts
  src/hooks/auth/useLoginHandler.ts
  src/hooks/auth/useRegisterHandler.ts
  src/hooks/auth/useResetPasswordHandler.ts
  src/pages/login.tsx
  src/pages/register.tsx
  src/utils/schemas/auth.ts
  yarn.lock
Labels: ✨ FEATURE, ♻️ REFACTOR

#32 ✨FEATURE: loading spinner
  package.json
  src/components/commons/Button/index.tsx
  src/components/commons/Spinner/Spinner.stories.tsx
  src/components/commons/Spinner/index.tsx
  yarn.lock
Labels: ✨ FEATURE

#29 ✨ FEATURE: image input 생성
  .env
  .eslintrc.json
  @types/group.ts
  public/icons/icon_close.svg
  public/icons/icon_edit.svg
  public/icons/icon_image.svg
  public/icons/icon_member_large.svg
  public/icons/icon_myprofile.svg
  public/icons/icon_plus_large.svg
  src/components/commons/Button/TextButton/index.tsx
  src/components/commons/Button/index.tsx
  src/components/commons/Input/ImageInput/ImageInput.stories.tsx
  src/components/commons/Input/ImageInput/index.tsx
  src/constants/errorMessage.ts
  src/hooks/useImageInput.ts
  src/middleware.ts
  src/pages/api/groupApi.ts
  src/pages/index.tsx
  src/styles/globals.css
  src/utils/icon.ts
  tailwind.config.ts
Labels: ✨ FEATURE

#31 🎨 STYLE : /login 페이지 ui 설정
  src/components/auth/LoginForm.tsx
  src/pages/login.tsx
Labels: 🎨 STYLE

#36 ♻️ REFACTOR: 모달 훅 props 수정
  src/components/commons/Button/index.tsx
  src/hooks/useModal.ts
  src/store/useModalStore.ts
Labels: ♻️ REFACTOR

#21 ✨ FEATURE: 소셜 로그인 기능 추가
  .env
  @types/auth.ts
  src/components/commons/SocialLoginBox/index.tsx
  src/pages/login.tsx
  src/pages/oauth/[provider].tsx
  src/utils/auth.ts
Labels: ✨ FEATURE

#38 ✨FEATURE: page routing 설정
  src/api/articleApi.ts
  src/api/articleCommentApi.ts
  src/api/authApi.ts
  src/api/axios.ts
  src/api/commentApi.ts
  src/api/groupApi.ts
  src/api/imageApi.ts
  src/api/taskApi.ts
  src/api/taskListApi.ts
  src/api/userApi.ts
  src/components/auth/SendMailModal.tsx
  src/components/commons/Button/index.tsx
  src/hooks/auth/useLoginHandler.ts
  src/hooks/auth/useRegisterHandler.ts
  src/hooks/auth/useResetPasswordHandler.ts
  src/middleware.ts
  src/pages/add-team.tsx
  src/pages/board/[boardId]/edit.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/board/add.tsx
  src/pages/board/index.tsx
  src/pages/join-team.tsx
  src/pages/login.tsx
  src/pages/oauth/[provider].tsx
  src/pages/teams/[teamId]/edit.tsx
  src/pages/teams/[teamId]/index.tsx
  src/pages/teams/[teamId]/task-list/[taskListId].tsx
  src/pages/teams/index.tsx
  src/pages/user/edit.tsx
  src/pages/user/history.tsx
Labels: ✨ FEATURE

#39 🐛HOTFIX: 리다이렉트 버그 수정
  .env
  src/components/auth/SendMailModal.tsx
  src/constants/.gitkeep
  src/hooks/auth/useLoginHandler.ts
  src/hooks/auth/useRegisterHandler.ts
  src/hooks/auth/useResetPasswordHandler.ts
  src/middleware.ts
  src/pages/oauth/[provider].tsx
  src/pages/teams/index.tsx
  src/store/useAuthStore.ts
Labels: 🛠 FIX

#33 ✨FEATURE: /team 페이지 추가
  @types/group.ts
  public/images/.gitkeep
  public/images/no_content_image.png
  src/api/userApi.ts
  src/components/auth/LoginForm.tsx
  src/components/auth/RegisterForm.tsx
  src/components/commons/Button/index.tsx
  src/components/commons/modal/WarnModal.tsx
  src/components/team-list/DeleteTeamModal.tsx
  src/components/team-list/TeamItem.tsx
  src/components/team-list/TeamList.tsx
  src/hooks/auth/useAuthHandler.ts
  src/hooks/auth/useLoginHandler.ts
  src/hooks/auth/useRegisterHandler.ts
  src/hooks/useModal.ts
  src/middleware.ts
  src/pages/teams/index.tsx
  src/store/useModalStore.ts
Labels: ✨ FEATURE

#41 ✨ FEATURE: Header
  @types/user.ts
  public/icons/icon_plus.svg
  public/images/logo.png
  src/api/userApi.ts
  src/components/Header/index.tsx
  src/components/commons/Popover/EditDeletePopover.tsx
  src/components/commons/Popover/ProfilePopover.tsx
  src/components/commons/Popover/TeamListPopover.tsx
  src/components/commons/Popover/index.tsx
  src/components/team-list/TeamItem.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: ✨ FEATURE

#37 ✨FEATURE: 팀생성하기 페이지 생성
  public/icons/icon_image.svg
  src/api/groupApi.ts
  src/components/add-team/add-team-form/index.tsx
  src/components/commons/Button/index.tsx
  src/components/commons/Input/ImageInput/index.tsx
  src/hooks/useAddTeamForm.ts
  src/pages/add-team.tsx
  src/styles/globals.css
Labels: ✨ FEATURE

#40 ✨FEATURE: 회원 탈퇴 기능, 유저 정보 쿼리 저장/유지 로직 추가
  public/icons/icon_delete_account.svg
  src/components/Header/index.tsx
  src/components/auth/RegisterForm.tsx
  src/components/auth/UserInfo.tsx
  src/components/editUser/DeleteAccount.tsx
  src/components/editUser/DeleteAccountModal.tsx
  src/components/teams/DeleteTeamModal.tsx
  src/components/teams/TeamItem.tsx
  src/components/teams/TeamList.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useAuthHandler.ts
  src/pages/_app.tsx
  src/pages/oauth/[provider].tsx
  src/pages/teams/index.tsx
  src/pages/user/edit.tsx
  src/store/useAuthStore.ts
  src/styles/globals.css
  src/utils/auth.ts
  src/utils/icon.ts
Labels: ✨ FEATURE

#42 ✨ FEATURE: toast 알림 기능 추가
  @types/commons.ts
  public/icons/icon_toast_danger.svg
  public/icons/icon_toast_info.svg
  public/icons/icon_toast_success.svg
  public/icons/icon_toast_warning.svg
  src/components/commons/Toast/index.stories.tsx
  src/components/commons/Toast/index.tsx
  src/hooks/auth/useAuthHandler.ts
  src/hooks/useToast.ts
  src/pages/_app.tsx
  src/store/useToastStore.ts
  src/utils/icon.ts
  tailwind.config.ts
Labels: ✨ FEATURE

#43 ✨ FEATURE: Dropdown
  src/components/Header/index.tsx
  src/components/commons/Dropdown/index.tsx
  src/components/commons/Popover/index.tsx
  src/pages/index.tsx
Labels: ✨ FEATURE

#46 ✨ FEATURE: 유저 정보 store 저장 - 로그인 유지
  @types/user.ts
  public/icons/icon_crown.svg
  src/components/Header/DesktopNavigation.tsx
  src/components/Header/Logo.tsx
  src/components/Header/MobileMenuButton.tsx
  src/components/Header/Sidebar.tsx
  src/components/Header/UserPopoverMenu.tsx
  src/components/Header/index.tsx
  src/components/auth/UserInfo.tsx
  src/components/commons/Dropdown/index.tsx
  src/components/commons/Popover/index.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useAuthHandler.ts
  src/hooks/useHeaderLogic.ts
  src/pages/_app.tsx
  src/utils/icon.ts
Labels: ✨ FEATURE, ♻️ REFACTOR

#45 ✨ FEATURE: 댓글 기능 추가
  .env.development
  .env.production
  .gitignore
  @types/articleComment.ts
  @types/task.ts
  @types/taskComment.ts
  package.json
  src/api/articleCommentApi.ts
  src/api/taskCommentApi.ts
  src/components/board-details/ArticleCommentList/index.tsx
  src/components/commons/Comment/CommentModal.tsx
  src/components/commons/Comment/index.stories.tsx
  src/components/commons/Comment/index.tsx
  src/components/commons/Comment/useComment.ts
  src/components/commons/Dropdown/index.tsx
  src/components/commons/NameTag/index.tsx
  src/components/commons/TextArea/index.stories.tsx
  src/components/commons/TextArea/index.tsx
  src/components/task-list/TaskCommentList/index.stories.tsx
  src/components/task-list/TaskCommentList/index.tsx
  src/constants/ArticleCommentLimit.ts
  src/constants/urlPattern.ts
  src/hooks/comment/useDeleteComment.ts
  src/hooks/comment/useEditComment.ts
  src/hooks/useObserver.ts
  src/pages/index.tsx
  src/utils/checkIsLink.ts
  src/utils/sortCommentList.ts
  src/utils/typeGuard/isTaskCommentType.ts
  yarn.lock
Labels: ✨ FEATURE

#47 ✨ FEATURE: MyHistoryPage
  @types/task.ts
  @types/user.ts
  src/api/userApi.ts
  src/components/my-history/TaskHistory.tsx
  src/pages/user/history.tsx
Labels: ✨ FEATURE

#49 ✨ FEATURE: 계정 설정 페이지
  @types/auth.ts
  @types/user.ts
  src/api/userApi.ts
  src/components/add-team/add-team-form/index.tsx
  src/components/commons/Input/index.tsx
  src/components/commons/modal/TwoInputModal.tsx
  src/components/editUser/ChangePassword.tsx
  src/components/editUser/ChangePasswordModal.tsx
  src/components/editUser/DeleteAccount.tsx
  src/components/editUser/EditUserForm.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/useAddTeamForm.ts
  src/hooks/useUpdateForm.ts
  src/pages/login.tsx
  src/pages/register.tsx
  src/pages/teams/index.tsx
  src/pages/user/edit.tsx
  src/utils/schemas/auth.ts
Labels: ✨ FEATURE

#53 ✨ FEATURE: CircleProgressBar
  src/components/TeamDetailPage/CircleProgressBar.tsx
  src/pages/teams/[teamId]/index.tsx
Labels: ✨ FEATURE

#55 ✨ FEATURE: JoinTeamPage
  src/constants/errorMessage.ts
  src/constants/urlPattern.ts
  src/hooks/useInvitation.ts
  src/hooks/useJoinTeam.ts
  src/pages/join-team.tsx
  src/utils/getParams.ts
  src/utils/validateImage.ts
Labels: ✨ FEATURE

#50 ✨ FEATURE: article details section
  .eslintrc.json
  @types/article.ts
  next.config.mjs
  public/icons/icon_heart_fill.svg
  src/api/articleApi.ts
  src/components/Header/DesktopNavigation.tsx
  src/components/Header/Sidebar.tsx
  src/components/board/ArticleDetail/DeleteArticleModal.tsx
  src/components/board/ArticleDetail/index.tsx
  src/components/board/ArticleSection/ArticleCard.tsx
  src/components/commons/NameTag/index.tsx
  src/pages/_app.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/board/index.tsx
  src/utils/icon.ts
Labels: ✨ FEATURE

#52 ✨ FEATURE: comment section
  src/components/board/ArticleDetail/CommentSection.tsx
  src/pages/index.tsx
Labels: ✨ FEATURE

#56 ♻️ REFACTOR: 헤더 데이터 요청 로직 수정, UI/UX 개선
  @types/user.ts
  src/components/Header/DesktopNavigation.tsx
  src/components/Header/index.tsx
  src/components/add-team/add-team-form/index.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/RegisterForm.tsx
  src/components/auth/ResetPasswordForm.tsx
  src/components/auth/SendMailModal.tsx
  src/components/editUser/ChangePasswordModal.tsx
  src/components/editUser/DeleteAccount.tsx
  src/components/editUser/EditUserForm.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useAuthForm.ts
  src/hooks/auth/useResetPasswordHandler.ts
  src/hooks/useHeaderLogic.ts
  src/hooks/useUpdateForm.ts
  src/middleware.ts
  src/pages/index.tsx
  src/pages/oauth/[provider].tsx
  src/pages/teams/[teamId]/index.tsx
  src/pages/teams/index.tsx
  src/store/useAuthStore.ts
Labels: ♻️ REFACTOR

#59 ✨FEATURE: create task
  @types/group.ts
  @types/task.ts
  package.json
  public/icons/icon_close.svg
  src/api/taskApi.ts
  src/api/taskListApi.ts
  src/components/commons/Dropdown/index.tsx
  src/components/commons/modal/AddTaskListModal.tsx
  src/components/commons/modal/OneInputModal.tsx
  src/components/task-list-page/Calendar.tsx
  src/components/task-list-page/CreateTaskModal.tsx
  src/components/task-list-page/DateWithCalendar.tsx
  src/components/task-list-page/FrequencyDropdown.tsx
  src/components/task-list-page/SelectedTimeAndDate.tsx
  src/components/task-list-page/Task.tsx
  src/components/task-list-page/TaskList.tsx
  src/components/task-list-page/Time.tsx
  src/components/task-list-page/WeeklyRepeatSelector.tsx
  src/hooks/useOutsideClick.ts
  src/pages/teams/[teamId]/task-lists/[taskListsId]/index.tsx
  tailwind.config.ts
  yarn.lock
Labels: ✨ FEATURE

#60 ✨FEATURE: 할 일 삭제 모달 연결
  src/api/taskApi.ts
  src/components/task-list-page/DeleteModal.tsx
  src/components/task-list-page/Task.tsx
Labels: ✨ FEATURE

#61 ✨FEATURE: 할 일 수정 모달
  src/components/commons/TextArea/index.tsx
  src/components/task-list-page/CreateTaskModal.tsx
  src/components/task-list-page/EditTaskModal.tsx
  src/components/task-list-page/SelectedTimeAndDate.tsx
  src/components/task-list-page/Task.tsx
  src/components/task-list-page/TimeSelector.tsx
  src/pages/teams/[teamId]/task-lists/[taskListsId]/index.tsx
Labels: ✨ FEATURE

#62 ✨FEATURE: 팀 수정 페이지
  src/components/add-team/add-team-form/index.tsx
  src/components/commons/Toast/index.tsx
  src/components/commons/UpdateTeam/index.tsx
  src/components/edit-team/EditTeamForm.tsx
  src/components/editUser/EditUserForm.tsx
  src/hooks/useHeaderLogic.ts
  src/hooks/useImageInput.ts
  src/hooks/useUpdateForm.ts
  src/pages/add-team.tsx
  src/pages/teams/[teamId]/edit.tsx
Labels: ✨ FEATURE

#64 ✨ FEATURE: Team Page 완성
  src/components/TeamDetailPage/ReportSection.tsx
  src/components/TeamDetailPage/TaskListItem.tsx
  src/components/TeamDetailPage/TaskListSection.tsx
  src/components/commons/Popover/index.tsx
  src/components/commons/modal/AddOrEditTaskListModal.tsx
  src/components/commons/modal/AddTaskListModal.tsx
  src/components/task-list-page/DateWithCalendar.tsx
  src/pages/teams/[teamId]/index.tsx
Labels: ✨ FEATURE

#66 ✨FEATURE: 로딩 / 에러 페이지 생성
  package.json
  public/favicon.ico
  public/icons/icon_fried_egg.svg
  public/lottie/animation_error.json
  public/lottie/animation_loading.json
  public/lottie/animation_success.json
  src/components/Header/Logo.tsx
  src/components/commons/Loading/index.tsx
  src/components/commons/LottieAnimation/index.tsx
  src/components/commons/Spinner/index.tsx
  src/components/commons/Success/index.tsx
  src/components/commons/modal/AddOrEditTaskListModal.tsx
  src/components/task-list-page/TaskList.tsx
  src/pages/404.tsx
  src/pages/add-team.tsx
  src/pages/teams/[teamId]/task-lists/[taskListsId]/index.tsx
  src/utils/icon.ts
  yarn.lock
Labels: ✨ FEATURE

#67 🎨 STYLE : toast 수정
  public/icons/icon_toast_danger.svg
  public/icons/icon_toast_info.svg
  public/icons/icon_toast_success.svg
  public/icons/icon_toast_warning.svg
  src/components/commons/Toast/index.tsx
  src/components/commons/modal/AddOrEditTaskListModal.tsx
Labels: 🎨 STYLE

#70 ✨FEATURE: tasklist refactoring
  @types/task.ts
  @types/taskComment.ts
  package.json
  src/components/TeamDetailPage/TaskListItem.tsx
  src/components/commons/Button/LinkButton/index.tsx
  src/components/commons/Button/TextButton.stories.tsx
  src/components/commons/Button/TextButton.tsx
  src/components/commons/Input/ImageInput.stories.tsx
  src/components/commons/Input/ImageInput.tsx
  src/components/commons/LottieAnimation/Loading.tsx
  src/components/commons/LottieAnimation/Success.tsx
  src/components/commons/modal/WarnModal.tsx
  src/components/task-list-page/CheckButton.tsx
  src/components/task-list-page/CreateTaskModal.tsx
  src/components/task-list-page/DateSelector.tsx
  src/components/task-list-page/FrequencyDropdown.tsx
  src/components/task-list-page/SelectedTimeAndDate.tsx
  src/components/task-list-page/Sidebar.tsx
  src/components/task-list-page/Task.tsx
  src/components/task-list-page/TaskList.tsx
  src/components/task-list-page/TimeSelector.tsx
  src/pages/teams/[teamId]/task-lists/[taskListsId]/index.tsx
  src/styles/globals.css
  tailwind.config.ts
  yarn.lock
Labels: ♻️ REFACTOR

#69 🛠 FIX: Theme 기능 제거 및 기타 컴포넌트들 수정
  package.json
  src/components/Header/Sidebar.tsx
  src/components/board/BoardForm/BoardForm.tsx
  src/components/commons/Input/ImageInput.tsx
  src/components/commons/Popover/index.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/teams/[teamId]/index.tsx
  src/pages/teams/[teamId]/task-lists/[taskListsId]/index.tsx
  src/styles/globals.css
  tailwind.config.ts
  yarn.lock
Labels: 🛠 FIX

#75 ♻️ REFACTOR: 수정 페이지 리펙터링
  @types/commons.ts
  @types/user.ts
  src/api/groupApi.ts
  src/components/add-team/add-team-form/index.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/RegisterForm.tsx
  src/components/commons/Input/ImageInput.tsx
  src/components/edit-team/EditTeamForm.tsx
  src/components/editUser/ChangePasswordModal.tsx
  src/components/editUser/EditUserForm.tsx
  src/hooks/auth/useAuthHandler.ts
  src/hooks/useAddTeamForm.ts
  src/hooks/useImageInput.ts
  src/hooks/useUpdateForm.ts
  src/pages/login.tsx
  src/pages/register.tsx
  src/pages/reset-password.tsx
Labels: 🛠 FIX, ♻️ REFACTOR

#72 ✨ FEATURE: 게시글 상세보기 댓글리스트 기능
  @types/articleComment.ts
  src/components/board/ArticleDetail/CommentList.tsx
  src/components/board/ArticleDetail/CommentSection.tsx
  src/components/board/ArticleDetail/index.tsx
  src/components/commons/TextArea/index.tsx
  src/pages/board/[boardId]/index.tsx
Labels: ✨ FEATURE

#71 ♻️ REFACTOR: 할일 상세보기 사이드바
  src/components/task-list-page/Task.tsx
  src/components/task-list-page/TaskList.tsx
  src/components/task-list-page/sidebar/CommentInput.tsx
  src/components/task-list-page/sidebar/index.tsx
Labels: ♻️ REFACTOR

#74 🛠 FIX: useJoinTeam 버그 수정
  src/hooks/useJoinTeam.ts
Labels: 🛠 FIX

#76 🛠 FIX: myhistorypage 렌더링 버그 수정
  @types/user.ts
  src/api/userApi.ts
  src/components/my-history/TaskHistory.tsx
Labels: 🛠 FIX

#79 🚀 DEPLOY: 빌드 에러 수정
  src/components/board/ArticleDetail/CommentSection.tsx
  src/components/my-history/TaskHistory.tsx
Labels: 🚀 DEPLOY

#80 ♻️ REFACTOR: 이미지 삭제 기능, api 요청 수정
  @types/group.ts
  src/components/Header/DesktopNavigation.tsx
  src/components/auth/SendMailModal.tsx
  src/components/board/ArticleDetail/CommentSection.tsx
  src/components/commons/Input/ImageInput.tsx
  src/components/commons/LottieAnimation/Loading.tsx
  src/components/commons/NameTag/index.tsx
  src/components/commons/Popover/index.tsx
  src/components/edit-team/EditTeamForm.tsx
  src/components/editUser/EditUserForm.tsx
  src/components/teams/TeamItem.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/useHeaderLogic.ts
  src/hooks/useUpdateForm.ts
  src/pages/_app.tsx
  src/pages/oauth/[provider].tsx
Labels: 🛠 FIX, ♻️ REFACTOR

#82 🛠 FIX: 버그 수정, 빌드 경고 수정
  .env.development
  .env.production
  .eslintrc.json
  src/api/taskListApi.ts
  src/components/board/ArticleDetail/CommentSection.tsx
  src/components/board/ArticleSection/ArticleCard.tsx
  src/components/board/BestArticleSection/BestArticlesCard.tsx
  src/components/commons/SocialLoginBox/index.tsx
  src/components/task-list-page/TaskList.tsx
  src/components/task-list-page/sidebar/index.tsx
  src/components/teams/TeamItem.tsx
  src/pages/board/index.tsx
  src/pages/login.tsx
  src/pages/oauth/[provider].tsx
  src/store/useModalStore.ts
Labels: 🛠 FIX

#83 ✨ FEATURE: DND
  next.config.mjs
  package.json
  src/api/taskApi.ts
  src/api/taskListApi.ts
  src/components/TeamDetailPage/TaskListItem.tsx
  src/components/TeamDetailPage/TaskListSection.tsx
  src/components/commons/modal/AddOrEditTaskListModal.tsx
  src/components/task-list-page/CreateTaskModal.tsx
  src/components/task-list-page/DeleteModal.tsx
  src/components/task-list-page/EditTaskModal.tsx
  src/components/task-list-page/Task.tsx
  src/components/task-list-page/TaskList.tsx
  src/components/task-list-page/sidebar/index.tsx
  src/hooks/useTaskListPageDnd.ts
  src/hooks/useTeamPageDnd.ts
  src/pages/teams/[teamId]/task-lists/[taskListsId]/index.tsx
  yarn.lock
Labels: ✨ FEATURE

#85 🛠 HOTFIX: 무한루프 버그 수정 (로딩 제거)
  src/components/commons/Input/ImageInput.tsx
  src/components/commons/TeamDefault/index.tsx
  src/components/teams/TeamItem.tsx
  src/components/teams/TeamList.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/useHeaderLogic.ts
  src/pages/_app.tsx
  src/pages/login.tsx
  src/pages/oauth/[provider].tsx
Labels: 🛠 FIX

#86 🛠 FIX: added slash
  src/pages/login.tsx
  src/pages/oauth/[provider].tsx
Labels: 🛠 FIX

#87 ♻️ REFACTOR: mobile refactor
  public/icons/icon_arrow_left_gray.svg
  public/icons/icon_arrow_right_gray.svg
  src/components/board/ArticleDetail/CommentSection.tsx
  src/components/board/ArticleDetail/index.tsx
  src/components/board/ArticleSection/ArticleCard.tsx
  src/components/board/pagination.tsx
  src/components/commons/modal/ModalWrapper.tsx
  src/components/task-list-page/DeleteModal.tsx
  src/components/task-list-page/EditTaskModal.tsx
  src/components/task-list-page/sidebar/index.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/usePagination.ts
  src/pages/board/index.tsx
Labels: ♻️ REFACTOR

#88 🛠 FIX: tasklist fix
  public/icons/icon_crown_small.svg
  public/icons/icon_toast_danger.svg
  public/icons/icon_toast_info.svg
  public/icons/icon_toast_success.svg
  public/icons/icon_toast_warning.svg
  src/api/taskApi.ts
  src/components/TeamDetailPage/TaskListSection.tsx
  src/components/commons/Button/index.tsx
  src/components/commons/Label/index.tsx
  src/components/commons/Popover/index.tsx
  src/components/commons/TeamDefault/index.tsx
  src/components/commons/Toast/index.tsx
  src/components/commons/UpdateTeam/index.tsx
  src/components/commons/modal/AddOrEditTaskListModal.tsx
  src/components/commons/modal/OneInputModal.tsx
  src/components/task-list-page/CreateTaskModal.tsx
  src/components/task-list-page/DeleteModal.tsx
  src/components/task-list-page/Task.tsx
  src/components/teams/TeamItem.tsx
  src/constants/globalConstants.ts
  src/pages/add-team.tsx
  src/pages/board/index.tsx
  src/pages/join-team.tsx
  src/pages/teams/[teamId]/task-lists/[taskListsId]/index.tsx
  src/pages/user/edit.tsx
  src/pages/user/history.tsx
  src/utils/icon.ts
  tailwind.config.ts
Labels: 🛠 FIX

#89 🎨 STYLE: 로그인, 회원가입 페이지 스타일 수정 및 소셜로그인 추가, 관련 로직 수정
  src/components/commons/SocialLoginBox/index.tsx
  src/components/edit-team/EditTeamForm.tsx
  src/components/editUser/EditUserForm.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/useSocialLogin.ts
  src/pages/join-team.tsx
  src/pages/login.tsx
  src/pages/register.tsx
Labels: 🎨 STYLE

#90 ♻️ REFACTOR : modify delete modal
  src/components/Header/Logo.tsx
  src/components/TeamDetailPage/MemberCard.tsx
  src/components/TeamDetailPage/TaskListSection.tsx
  src/components/commons/Button/index.tsx
  src/components/commons/Input/ImageInput.tsx
  src/components/commons/NameTag/index.tsx
  src/components/commons/Popover/EditDeletePopover.tsx
  src/components/commons/Popover/index.tsx
  src/components/commons/TeamDefault/index.tsx
  src/components/commons/Toast/index.tsx
  src/components/commons/UpdateTeam/index.tsx
  src/components/task-list-page/CheckButton.tsx
  src/components/task-list-page/CreateTaskModal.tsx
  src/components/task-list-page/DeleteModal.tsx
  src/components/task-list-page/EditTaskModal.tsx
  src/components/task-list-page/Task.tsx
  src/components/teams/TeamItem.tsx
  src/constants/globalConstants.ts
  src/pages/join-team.tsx
  src/pages/login.tsx
  src/pages/register.tsx
  src/pages/teams/[teamId]/task-lists/[taskListsId]/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🛠 FIX, ♻️ REFACTOR, 🎨 STYLE

#91 ✨ FEATURE: useJoinTeam 경우의 수 추가
  src/hooks/useJoinTeam.ts
Labels: ✨ FEATURE

#93 🛠 FIX: dnd 버그 수정, 스타일 체인지
  src/components/TeamDetailPage/TaskListItem.tsx
  src/components/TeamDetailPage/TaskListSection.tsx
  src/hooks/useTeamPageDnd.ts
Labels: 🛠 FIX, 🎨 STYLE

#92 ♻️ REFACTOR : 닉네임 유효성 검사, 팀 생성 헤더 반영, 여러 UI 수정
  src/components/Header/UserPopoverMenu.tsx
  src/components/commons/NameTag/index.tsx
  src/components/commons/Popover/index.tsx
  src/components/edit-team/EditTeamForm.tsx
  src/components/editUser/EditUserForm.tsx
  src/hooks/useAddTeamForm.ts
  src/hooks/useUpdateForm.ts
  src/pages/teams/index.tsx
  src/utils/schemas/auth.ts
Labels: 🛠 FIX, ♻️ REFACTOR

#95 🎨 STYLE: Header, Dropdown, add-board, TeamPage UI 수정
  public/favicon.ico
  public/icons/icon_tamagotchi.svg
  src/components/Header/Logo.tsx
  src/components/Header/Sidebar.tsx
  src/components/TeamDetailPage/MemberCard.tsx
  src/components/TeamDetailPage/MembersSection.tsx
  src/components/TeamDetailPage/ReportSection.tsx
  src/components/TeamDetailPage/TaskListSection.tsx
  src/components/TeamDetailPage/TeamTitle.tsx
  src/components/board/BoardForm/BoardForm.tsx
  src/components/commons/Dropdown/index.tsx
  src/pages/teams/[teamId]/index.tsx
  src/utils/icon.ts
  tailwind.config.ts
Labels: 🎨 STYLE

#96 ♻️ REFACTOR: Refactor
  src/components/commons/modal/OneInputModal.tsx
  src/components/commons/modal/TwoInputModal.tsx
  src/components/task-list-page/EditTaskModal.tsx
  src/components/task-list-page/sidebar/index.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/board/index.tsx
Labels: ♻️ REFACTOR

#97 ♻️ REFACTOR : error-boundary 적용
  src/components/commons/Comment/index.tsx
  src/components/commons/ErrorBoundary/index.tsx
  src/components/commons/TextArea/index.tsx
  src/components/task-list-page/sidebar/CommentInput.tsx
  src/components/teams/TeamList.tsx
  src/pages/_app.tsx
  src/pages/teams/index.tsx
Labels: ♻️ REFACTOR

#98 ♻️ REFACTOR : 페이지 로딩 처리, 코드 정리
  src/components/commons/NameTag/index.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useResetPasswordHandler.ts
  src/hooks/useUpdateForm.ts
  src/pages/_app.tsx
Labels: 🛠 FIX, ♻️ REFACTOR

#99 🛠 FIX: 이미지 관련 로직 수정 및 기능 추가
  next.config.mjs
  src/components/TeamDetailPage/TeamTitle.tsx
  src/components/commons/Input/ImageInput.tsx
  src/components/edit-team/EditTeamForm.tsx
  src/hooks/useUpdateForm.ts
  src/pages/teams/[teamId]/index.tsx
  src/utils/validateImage.ts
Labels: ✨ FEATURE, 🛠 FIX, 🎨 STYLE

#100 🎨 STYLE: edited teamTitle (FE-156)
  src/components/TeamDetailPage/TeamTitle.tsx
  src/pages/_app.tsx
Labels: 🎨 STYLE

#101 🎨 STYLE: Landing Page Image Change
  public/images/landing-comments.png
  public/images/landing-invite-page.png
  public/images/team_page_image.png
  src/pages/index.tsx
Labels: 🎨 STYLE

#102 🛠 FIX: 회원가입 실패 처리
  src/components/commons/Toast/index.tsx
  src/components/teams/TeamList.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useAuthHandler.ts
Labels: 🛠 FIX, ♻️ REFACTOR
